### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [dajare/j-s-fletcher_the-talleyrand-maxim#1]
# Semantics

- [x] chapter-18: You added `xml:lang="la"` on “re” but from [Merriam-Webster](https://www.merriam-webster.com/dictionary/re) that appears to be a valid English preposition.
- [x] chapter-16: I think the final quote from the paper (“Information wanted about James Parrawhite”) should be a blockquote. I don’t think it makes sense to have a `<b>` in spoken dialogue that isn’t also a blockquote.
- [x] chapter-24: I don’t think “alias” in `Parrawhite, <em>alias</em> Parsons` should be italicized or considered emphasis. I think when this book was originally published they might have been treating it as a Latin term (short for “alias dictus”). I think in modern usage it doesn’t need italics when it’s being used as an adverb.

# Spelling

- [x] chapter-20: modernize-spelling turned “tho’” into “though” in a paragraph where the landlord is speaking and using lots of elision. The use of elision here seems clearly intentional to me, so we should revert this change back to the original. 

# Style

- [x] I think your styling for the chapter-21 list is overly intricate and somewhat undermines the meaning of an ordered list by putting the bullets inside the list items. I think you can just get rid of the bespoke CSS and delete the quotation mark and number at the start of each `<li`>. I think if you just add a `”` at the end of the last list item, you will get the point across that all of this is spoken. So something like:

```
<ol>
	<li>
		<p><abbr>Mr.</abbr> Bartle is seen by his shop-boy to take a certain paper from a book which came from the late John Mallathorpe’s office at Mallathorpe Mill. He puts that paper in his pocket.</p>
	</li>
	... more list items
	<li>
		<p>And last⁠—in all such schemes as Pratt’s, the schemer invariably forgets something. Pratt forgot that there might arise what actually has arisen⁠—inquiry for Parrawhite. The search for Parrawhite is afoot⁠—and if you want to get at Pratt, it will have to be through what I firmly believe to be a fact⁠—his murder of Parrawhite and his disposal of Parrawhite’s body.”</p>
	</li>
</ol>
```

- [x] `#chapter-10 header > p:first-of-type` can be simplified to `#chapter-10 header p`. Also, it should be the same as the [7.2.10.8](https://standardebooks.org/manual/1.7.0/7-high-level-structural-patterns#7.2.10.8) CSS (so `margin: 1em;` instead of `margin: 1em 0;`).

# Colophon

- [x] We shouldn’t link to non-English Wikipedia in the colophon, for the cover artist. Lint flags this too.

**Comment by dajare** [comment]
Thanks, @weijia-cheng - I really appreciate your sharpness and clarity in these reviews! Some quick commentary on select points:

- **Semantics** : it wasn't clear to me whether the c16 change would be regarded as \[Editorial\], so I went with caution and put that in a separate, editorial commit. Easy enough to change the message when it's on its own.
- **Spelling** : good catch!
- **Style** : I've simply followed (I hope!) your recommendations for c21. That's slightly odd for continued speech convention in print, but at least Fletcher's prose as it ends (the next para, actually) makes crystal clear who is speaking. I toyed with the idea of using css-counters to preserve the opening quotes with each paragraph. We'll see what the editor-in-chief makes of it! :grimacing: 
- no idea what I was thinking in c10's CSS! :/
- **Colophon** : I understand about en-language wiki; wee shame, I think, that a full entry on a non-en wiki is prohibited but there's always Google (or DDG, or whatever) for those who are interested.

I hope I managed to catch everything this time! There might be follow-up to c16, but if you're happy, then over to Alex? Thanks again!

**Comment by dajare** [comment]
+ Just re-read my long description and realized I had a problematic tense ("was" > "is"). Sorry about that! Now also commited.

**Comment by weijia-cheng** [comment]
Ok, just two minor follow-ups:

- [ ] The blockquote change in chapter-16 can be non-editorial since it doesn't touch the actual text, just the semantics/typesetting, though I don't feel too strongly about changing it.
- [ ] We can add an se-lint-ignore.xml since lint is flagging chapter-21 since our list change.

**Comment by dajare** [comment]
OK @weijia-cheng  - both done. Hopefully ready for the next stage. 

(I don't think I'll be adding to your workload any time soon. :wink: )

Thanks again!
